/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#1c2028",
        "error-container": "#93000a",
        "secondary-container": "#03b5d3",
        "on-tertiary-container": "#0d0096",
        "surface-tint": "#adc6ff",
        "on-secondary-fixed-variant": "#004e5c",
        "surface": "#0f131c",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-surface": "#dfe2ee",
        "inverse-surface": "#dfe2ee",
        "outline": "#8c909f",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#00285d",
        "on-surface-variant": "#c2c6d6",
        "tertiary-container": "#8083ff",
        "secondary-fixed": "#acedff",
        "primary-container": "#4d8eff",
        "surface-dim": "#0f131c",
        "on-primary-fixed": "#001a42",
        "surface-bright": "#353942",
        "secondary": "#4cd7f6",
        "primary": "#adc6ff",
        "surface-container-highest": "#31353e",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#004395",
        "inverse-on-surface": "#2c3039",
        "on-background": "#dfe2ee",
        "primary-fixed": "#d8e2ff",
        "inverse-primary": "#005ac2",
        "secondary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed": "#07006c",
        "surface-container-low": "#181c24",
        "outline-variant": "#424754",
        "surface-container-lowest": "#0a0e16",
        "primary-fixed-dim": "#adc6ff",
        "surface-variant": "#31353e",
        "tertiary": "#c0c1ff",
        "on-tertiary": "#1000a9",
        "background": "#0f131c",
        "on-secondary": "#003640",
        "on-secondary-fixed": "#001f26",
        "on-primary": "#002e6a",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#00424e",
        "surface-container-high": "#262a33",
        "tertiary-fixed": "#e1e0ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-lg": "1.25rem",
        "gutter-mobile": "0.75rem",
        "margin-mobile": "1rem",
        "space-md": "0.75rem",
        "gutter": "1rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "margin": "1.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "label-badge": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "label-code-lg": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "label-code-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
        "label-code-lg": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
