/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "var(--color-surface-container)",
        "error-container": "var(--color-error-container)",
        "secondary-container": "var(--color-secondary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-tint": "var(--color-surface-tint)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface": "var(--color-surface)",
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
        "on-surface": "var(--color-on-surface)",
        "inverse-surface": "var(--color-inverse-surface)",
        "outline": "var(--color-outline)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary": "var(--color-secondary)",
        "primary": "var(--color-primary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "error": "var(--color-error)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-background": "var(--color-on-background)",
        "primary-fixed": "var(--color-primary-fixed)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "surface-container-low": "var(--color-surface-container-low)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-variant": "var(--color-surface-variant)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "background": "var(--color-background)",
        "on-secondary": "var(--color-on-secondary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-primary": "var(--color-on-primary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-lg": "1.25rem",
        "gutter-mobile": "0.75rem",
        "margin-mobile": "1rem",
        "space-md": "0.75rem",
        "gutter": "1rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "margin": "1.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "label-badge": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "label-code-lg": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "label-code-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
        "label-code-lg": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
